spring.application.name=InventoryMate

#server.port=8081
# Puerto dinámico de Railway
server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://root:jiEpnqgeyQujFOHkuZwnnvgpidUMpiXq@hopper.proxy.rlwy.net:58023/railway
spring.datasource.username=root
spring.datasource.password=jiEpnqgeyQujFOHkuZwnnvgpidUMpiXq
#spring.datasource.url=jdbc:mysql://localhost:3306/db_inventorymate?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=c07c89df370585c35e50a598eb4ad81138b00cf51de8b81609eedd6228331a48
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

azure.ai.endpoint=https://machine-learning-production-a71f.up.railway.app
